### ISSUE TITLE
No read of settings.xml when running 'mvn test'

### ISSUE THREAD

**Issue by mpet** [kubeshop/testkube-executor-maven#8] opened 2022-08-30 08:05 UTC
Hi,

When you run test cases with 'mvn test' this could involve building. This then involves downloading dependencies.
We have defined dependencies on our own internal nexus repo. To make sure maven uses it we have it set in our settings.xml for each user.

How can we use the local settings.xml in ~/.m2 when creating testcases?

br,

//mikael

**Comment by vLia** [comment] 2022-09-14 13:48
Closing this issue as it is a duplicate of https://github.com/kubeshop/testkube/issues/2185

**Closed by vLia** 2022-09-14 13:48 UTC
